apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-app-deployment
  labels:
    app: keda-app
spec:
  selector:
    matchLabels:
      app: keda-app
  replicas: 1
  template:
    metadata:
      labels:
        app: keda-app
    spec:
      containers:
        - name: keda-app-container
          image: "your_ecr_repo/kedaecr:latest"  # Replace with your ECR repo
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
